FROM python:2.7

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
RUN echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y git sqlite3 netcat mongodb-org-shell mongodb-org-tools

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

RUN chmod +x bootstrap.sh

EXPOSE 8080
CMD ./bootstrap.sh