version: '2'

services:
   db:
     image: mongo
     restart: always

   django:
     depends_on:
       - db
     build: ./
     links:
       - db:db
     ports:
       - "8080:8080"
     environment:
       DB: db
     restart: always